#!/usr/bin/env python3
"""User-facing dashboard for Confidence Core4 + separate Value list."""
from __future__ import annotations

def render_page()->str:
 return r'''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07101d"><title>Perşembe Karar Listesi V3</title><style>
:root{--bg:#07101d;--p:#0d1828;--p2:#111f32;--line:#243750;--txt:#f5f8fc;--muted:#91a5bd;--green:#43dfa8;--gold:#f5c45b;--blue:#70adff;--red:#ff7c82}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#06101d,#0a1422);color:var(--txt);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{max-width:1120px;margin:auto;padding:28px 18px 60px}.hero{display:flex;justify-content:space-between;gap:20px}.ey{font-size:12px;letter-spacing:.13em;color:var(--blue);font-weight:900}.hero h1{font-size:clamp(29px,5vw,44px);margin:7px 0 9px}.hero p{max-width:800px;color:var(--muted);line-height:1.55;margin:0}.stamp{font-size:12px;color:var(--muted);white-space:nowrap}.panel{margin-top:20px;background:var(--p);border:1px solid var(--line);border-radius:20px;overflow:hidden;box-shadow:0 18px 45px rgba(0,0,0,.22)}.head{padding:18px;border-bottom:1px solid var(--line)}.head h2{margin:0;font-size:20px}.head p{margin:6px 0 0;color:var(--muted);font-size:12px;line-height:1.45}.status{display:flex;justify-content:space-between;align-items:center;gap:14px}.badge{border-radius:999px;padding:8px 11px;font-size:11px;font-weight:900}.ok{color:var(--green);border:1px solid rgba(67,223,168,.35);background:rgba(67,223,168,.1)}.wait{color:var(--gold);border:1px solid rgba(245,196,91,.35);background:rgba(245,196,91,.1)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;padding:11px}.card{background:var(--p2);border:1px solid #243950;border-radius:15px;padding:15px}.card.core{border-color:rgba(67,223,168,.45)}.card.value{border-color:rgba(245,196,91,.42)}.teams{font-size:16px;font-weight:850}.sel{font-size:15px;margin-top:5px}.tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.tag{padding:5px 8px;border-radius:999px;font-size:10px;font-weight:850;border:1px solid #31506e;color:#c8dcf3}.tag.g{color:var(--green);border-color:rgba(67,223,168,.35)}.tag.v{color:var(--gold);border-color:rgba(245,196,91,.38)}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:12px}.m{background:#091523;border:1px solid #1d3047;border-radius:10px;padding:8px}.m span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.04em}.m b{display:block;margin-top:4px;font-size:13px}.m.good b{color:var(--green)}.m.gold b{color:var(--gold)}.empty{padding:28px;text-align:center;color:var(--muted);grid-column:1/-1}.note{padding:14px 18px;color:var(--muted);font-size:11px;line-height:1.5;border-top:1px solid var(--line)}button{background:#0e1d30;color:#dceafa;border:1px solid var(--line);padding:9px 12px;border-radius:10px;font-weight:750;cursor:pointer}@media(max-width:760px){.wrap{padding:20px 12px 42px}.hero{display:block}.stamp{margin-top:10px}.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><main class="wrap"><header class="hero"><div><div class="ey">FOOTBALL DECISION ENGINE · V3</div><h1>Perşembe Karar Listesi</h1><p>Güven ve Value artık ayrı ürünler. Güven Core4; V1, xG/xGA, rakip-ayarlı güç, Expected XI, Dixon–Coles ve multi-book no-vig piyasa uzlaşısından geçer. Value listesi ise Türkiye oranında fiyat avantajını ayrıca arar.</p></div><div class="stamp" id="updated">Kontrol ediliyor…</div></header>
<section class="panel"><div class="head status"><div><h2 id="st">Haftalık karar kontrol ediliyor</h2><p id="sd">Veriler okunuyor.</p></div><div style="display:flex;gap:8px;align-items:center"><button onclick="loadData()">Yenile</button><span class="badge wait" id="badge">BEKLENİYOR</span></div></div></section>
<section class="panel"><div class="head"><h2>🛡️ Güven Core4</h2><p>Oran burada seçim sebebi değildir. Öncelik konservatif olasılık alt sınırı, çoklu model uzlaşısı, kadro/veri kalitesi ve multi-book piyasa doğrulamasıdır.</p></div><div class="grid" id="trust"><div class="empty">Liste henüz kesinleşmedi.</div></div><div class="note">“Alt sınır” istatistiksel garanti değildir; model ailesi + piyasa arasındaki yayılım ve veri eksikliğini cezalandıran konservatif güven tabanıdır.</div></section>
<section class="panel"><div class="head"><h2>💰 Value Adayları</h2><p>Türkiye'deki oynanabilir oran, piyasa-ankorlu olasılığa göre pozitif beklenen değer üretiyorsa burada yer alır. Bir seçim Value olabilir ama Güven Core4 olmayabilir.</p></div><div class="grid" id="value"><div class="empty">Pozitif EV adayı henüz yok.</div></div></section>
</main><script>
const $=x=>document.getElementById(x),pct=x=>x==null?'—':(Number(x)*100).toFixed(1).replace('.',',')+'%',odd=x=>x==null?'—':Number(x).toFixed(2).replace('.',',');
function metric(k,v,c=''){let d=document.createElement('div');d.className='m '+c;d.innerHTML='<span></span><b></b>';d.children[0].textContent=k;d.children[1].textContent=v;return d}
function card(p,i,type){let d=document.createElement('article');d.className='card '+type;let teams=document.createElement('div');teams.className='teams';teams.textContent=`#${i+1} ${p.home||''} – ${p.away||''}`;let sel=document.createElement('div');sel.className='sel';sel.textContent=p.selection||p.market||'—';let tags=document.createElement('div');tags.className='tags';let a=document.createElement('span');a.className='tag '+(type==='core'?'g':'v');a.textContent=type==='core'?'GÜVEN':'VALUE';tags.append(a);if((p.international_bookmakers||0)>=2){let b=document.createElement('span');b.className='tag';b.textContent=`${p.international_bookmakers} BOOK`;tags.append(b)}if(p.xg_used){let b=document.createElement('span');b.className='tag';b.textContent='xG';tags.append(b)}if(p.dixon_coles_available){let b=document.createElement('span');b.className='tag';b.textContent='DIXON–COLES';tags.append(b)}let ms=document.createElement('div');ms.className='metrics';ms.append(metric('Konservatif alt',pct(p.confidence_lower_bound),'good'));ms.append(metric('Kalibre/ankor',pct(p.calibrated_probability)));ms.append(metric('Model medyan',pct(p.model_probability_estimate)));ms.append(metric('Dünya fair',pct(p.international_fair_probability)));ms.append(metric('Model uzlaşı',pct(p.direction_agreement),'good'));ms.append(metric('Kanıt kalitesi',pct(p.evidence_quality)));ms.append(metric('Türkiye oranı',odd(p.tr_price)));if(type==='value')ms.append(metric('Kalibre EV',pct(p.value_ev_calibrated??p.model_ev_vs_tr),'gold'));d.append(teams,sel,tags,ms);return d}
function render(id,arr,type,lim){let el=$(id);el.innerHTML='';let x=(arr||[]).slice(0,lim);if(!x.length){el.innerHTML='<div class="empty">Bu bölüm için kriterleri geçen seçim yok.</div>';return}x.forEach((p,i)=>el.append(card(p,i,type)))}
async function loadData(){try{let r=await fetch('/thursday-list',{cache:'no-store'}),d=await r.json();$('updated').textContent='Son kontrol: '+new Date().toLocaleString('tr-TR');let fin=d.status==='finalized';$('badge').className='badge '+(fin?'ok':'wait');$('badge').textContent=fin?'LİSTE HAZIR':'BEKLENİYOR';$('st').textContent=fin?'V3 haftalık karar hazır':'V3 karar henüz kesinleşmedi';$('sd').textContent=fin?'Güven ve Value ayrı değerlendirilmiştir.':'Multi-book, kadro, xG ve Türkiye fiyat kapsaması tamamlanınca karar oluşur.';if(fin){render('trust',d.high_confidence||[],'core',4);render('value',d.high_confidence_value||[],'value',10)}}catch(e){$('st').textContent='Bağlantı hatası';$('sd').textContent='Veri okunamadı.'}}
loadData();setInterval(loadData,60000);
</script></body></html>'''
